localauthor/zk

zk-index.el
zk.el

Dear Grant, 
this PR is a small addition to #5. The modification of `zk-index--format-candidates` ensures proper display of note titles in `*ZK-Index*` if `zk-file-name-separator` is set to something other than a space.
Best regards,
jgru

Replace separator in index

---

zk-consult.el
zk.el

Dear Grant, 
this PR aims at adding further support for `consult`-functions within `zk`.
It adds a function which could replace `zk--select-file` and therefore enables fast previews of files to open as well backlinks.
Thanks already in advance for having a look at it and letting me know what you think about it. 
Best regards,
jgru

Add note selection with consult

---

zk-index.el

(Hi! After getting frustrated with my home-grown Deft-based Zettelkasten implementation, I came upon your package and have been adapting both my existing structure to Zk and also adding some minor extensions to Zk to make that possible. So far, Zk has been able to handle my ~6400 notes much better than Deft. Thanks for publishing the package!)
This refactoring is not strictly necessary, but Iʹm uneasy about near-duplicate functions that would require keeping any changes in sync, so I combined them into one function. I can see why you had two, though; it was a nice programming puzzle to replicate the functionality within one function. I also added doc strings to the relevant variables.

Refactor zk-index-(focus|search)-mode-line into a single function

---

zk.el

Having notes split into subdirectories --- for example, one for each year --- makes it easier to handle the files outside of Emacs and Zk ecosystem.

Add option (zk-directory-recursive) to find files recursively

---

zk.el

Based on profiling, file-truename is an expensive operation, and file-in-directory-p calls it many times. Most of the time, callers of zk-file-p are not all that interested in making sure the file is indeed in zk-directory, just that it's a valid file that matches the zk-id-regexp. Functions that do need to check can pass STRICT optional argument.
I am doing this because I'm working on another feature, namely making titles in the file name optional, and this came up when factoring out code with hard-coded string-matching of file name.

Refactor zk-file-p to improve performance

---

zk-index.el

This allows easy access to zk-directory from the zk-index buffer by invoking dired or magit-status, for example.

Change zk-index to set Emacs default-directory to zk-directory

---

zk-index.el

This is especially important in `zk-index-button-display-action`, since the function is called for both zk-index and zk-desktop buttons, so opening any link gives an error from `file-in-directory-p`.

Fix handling of zk-index-desktop-directory not being set

---

README.org
zk-index.el
zk-link-hint.el
zk-org-link.el
zk.el

This way zk-link-regexp is generated at run-time, so it always reflects user
changes to zk-link-format and zk-id-regexp.

Bugfix: Change zk-link-regexp to macro of the same name

---

zk.el

Customizing this variable allows note creation and renaming commands to put notes in subdirectories under `zk-directory` for when `zk-directory-recursive' is set. One easy such function to have subdirectories for each year might be set like this:
``` emacs-lisp
(custom-set-variables '(zk-subdirectory-function (lambda (id) (seq-subseq id 0 4))))
```
I also extracted file path generating function `zk--note-file-path' from `zk-new-note' and `zk-rename-note', where this functionality was duplicated, so more difficult to change.

Feature: Add zk-subdirectory-function for determining subdirectory to put new notes in

---

zk-index.el
zk.el

This regexp is created several times thruoughout the code, so refactoring it
like this will make any future changes easier and less error-prone.
P.S. Flycheck is magical! Thanks for the tip.

Extract zk-file-name-regexp

---

zk.el

This has no effect on existing code, but allows easier creation of additional features, such as searching for zk files that /do not/ contain a certain phrase. Extended grep syntax is easier to write programmatically since don't need to do as much backslashing.
I also replaced the grep invocation in `zk--grep-file-list` with the spelled-out arguments, making it easier to tell at a glance what particular arguments do.

Feature: add options for extended and inverted grep

---

zk.el

Sorry, I apparently was thinking of something else while typing. I did more rigorous testing with ERT this time to make sure the function works as expected.

Fix a typo in zk--grep-file-list's grep command

---

zk.el

Using a lexical closure allows capturing the pre-formatted completion table rather than having the function re-calculate the same list from scratch at every change in input.
I tested this with ERT (Emacs Lisp Regression Tests) and ELP (Emacs Lisp Profiler). For 50 simulated completions, runtime went from around 50 seconds (first screenshot, "main") to less than 25 seconds (second screenshot):
[![2022-10-28-at-22-07-50.jpg](https://i.postimg.cc/Nfr7f6Tk/2022-10-28-at-22-07-50.jpg)](https://postimg.cc/HVd7676r)
[![2022-10-28-at-22-26-21.png](https://i.postimg.cc/cJRywtnp/2022-10-28-at-22-26-21.png)](https://postimg.cc/nshPtzT2)

Improve performance for zk-completion-at-point

---

zk-index.el
zk.el

The function `zk--current-id` is very limited in its use-cases, and its implementation duplicates some functionality (i.e., string-matching against `zk-file-name-regexp`). Adding zk--file-id as a utility function that is like a limited `zk-file-p` that returns a useful value makes it usable in a wider variety of situations.
Having to specify the target is a boon, I believe, since does not result in much longer invocation, but makes it very clear what exactly is "current" without having to look up whether the function uses `buffer-file-name` or `(buffer-file-name)` or something else entirely.
I did some ERT testing and have been using zk and zk-index this way for a few days at least, so everything works as expected.

Replace zk--current-id with more general function

---

zk-index.el
zk.el

There are several identical calls to` format-spec`, so making changes or customizing the way things are formatted (beyond the various `-format` variables) is difficult. Having one function that is always used for formatting `id` and `title` makes it possible to customize the behavior by advising the function.
All affected functions have been tested "in the field." I also took the opportunity to slightly refactor some of these factions (like replacing `(progn (string-match ... (when id` with `(when (string-match ...`) without changing functionality at all.

Extract direct references to format-spec into zk--format-spec

---

README.org
zk-desktop.el
zk-index.el
zk.el

@boyechko What do you think about `zk-desktop` being moved to its own package? The only reason they are both in `zk-index` is that I wrote them concurrently. Can be done pretty cleanly.

Decouple zk-desktop

---

zk-desktop.el

```
zk-desktop.el:196:2: Error: Symbol’s value as variable is void: zk-desktop-button-map
```

Fix byte-compile error

---

zk-index.el

Right now, it mentions `zk-comletion-at-point-format`, which is an artifact from `zk--format-candidates`. I also took the opportunity to rename internal variable `zk-index-format` to just `format`.

Update zk-index--format-candidates docstring to reference zk-index-format

---

zk.el

I thought I was being clever in "overloading" `zk--format` to call `zk-format-function` if it is set, and to do the default formatting otherwise. However, when writing `zk-format-function` for my use-case, I realized it would be useful to have an option of calling the default formatter in some cases. While it is possible to do that by lexically clearing `zk-format-function` before calling `zk--format`, that seems hacky:
``` emacs-lisp
(defun my-custom-zk-format (format id title)
(if (not (some-test-p id))
(let ((zk-format-function nil))
(zk--format format id title))
;; do the formatting on my own
...))
```
With this refactoring, the above can become:
``` emacs-lisp
(defun my-custom-zk-format (format id title)
(if (not (some-test-p id))
(zk--format-function format id title)
;; do the …
```

Refactor zk--format and zk-format-function

---

zk-org-link.el
zk.el

This changes `zk-link-format` to use same %-sequences as other `zk-*-format` variables.
Having consistent syntax is helpful to avoid mistakes. Additionally, this change allows 1) simplifying `zk--format` so it doesn't need to handle two different sets of %-sequences, and 2) experimenting with other link markup, such as `[[%i][%t]]` for org-mode links without explicit link type or `[[%i|%t]]` for syntax used by MediaWiki.
Also, `zk-link-regexp` function now accepts optional ID and/or title to generate a regexp matching specific links, so that with the default `zk-link-format`, `(zk-link-regexp "202307090142")` returns `"\\[\\[\\(?1:202307090142\\)]]"`. The explicitly numbered capture groups are consistent with `zk-file-name-regexp`.

Feature: Consisent zk-link-format

---

zk.el

Adds ability to customize tag insertion. Closes #73.
Maybe give this a try, @Alesnim?
here's the function I'm using:
```elisp
(defun gr/zk-insert-tag (tag)
(interactive)
(unless current-prefix-arg
(goto-char (point-min))
(when (re-search-forward "tags: " nil t)
(goto-char (match-beginning 0))
(end-of-line)
(insert " ")))
(insert tag))
(setq zk-tag-insert-function 'gr/zk-insert-tag)
```

Add zk-tag-insert-function

---

zk.el

If there is only one file under `zk-directory`, create new note via `zk-new-note` complains:  `zk--insert-link-and-title: Wrong type argument: listp, "202412042100"` .
The cause is `zk--id-list` does not return a list but rather a string if there is only one file under `zk-directory`. 
This change fixed it.

Fix bug that `zk--id-list` does not return list if there is only one file in zk-directory.
